import type { CatalogEntry } from "@/lib/engine/catalog";

export const ARIA_CATALOG: CatalogEntry[] = [
  // ── Manicure ──────────────────────────────────────────────────────────────
  {
    id: "nail-basic-mani",
    name: "Basic Manicure",
    category: "Manicure",
    priceLabel: "$25",
    durationMinutes: 30,
    durationLabel: "30 min",
    status: "online",
    popularRank: 3,
    keywords: [
      "manicure",
      "mani",
      "nails",
      "nail",
      "basic nails",
      "regular manicure",
      "polish",
      "regular polish",
    ],
    aliases: [
      { phrase: "basic manicure", weight: 1.0 },
      { phrase: "regular manicure", weight: 0.95 },
      { phrase: "manicure", weight: 0.95 },
      { phrase: "do my nails", weight: 0.85 },
      { phrase: "get my nails done", weight: 0.85 },
      { phrase: "nail appointment", weight: 0.8 },
    ],
    misspellings: ["manicur", "manicure", "nalis", "naill"],
  },
  {
    id: "nail-gel-mani",
    name: "Gel Manicure",
    category: "Manicure",
    priceLabel: "$45",
    durationMinutes: 50,
    durationLabel: "50 min",
    status: "online",
    popularRank: 1,
    keywords: [
      "gel",
      "gel nails",
      "gel manicure",
      "gel polish",
      "soft gel",
      "gel color",
      "long lasting",
      "no chip",
    ],
    aliases: [
      { phrase: "gel manicure", weight: 1.0 },
      { phrase: "gel nails", weight: 0.95 },
      { phrase: "gel polish", weight: 0.9 },
      { phrase: "shellac", weight: 0.85 },
      { phrase: "no chip manicure", weight: 0.85 },
    ],
    misspellings: ["gel nails", "jel nails", "gell"],
  },
  {
    id: "nail-acrylic-set",
    name: "Acrylic Full Set",
    category: "Manicure",
    priceLabel: "$65",
    durationMinutes: 75,
    durationLabel: "1 hr 15 min",
    status: "online",
    popularRank: 2,
    keywords: [
      "acrylic",
      "acrylics",
      "full set",
      "new set",
      "extensions",
      "nail extensions",
      "tips",
      "fake nails",
      "artificial nails",
      "press on",
    ],
    aliases: [
      { phrase: "acrylic full set", weight: 1.0 },
      { phrase: "full set of acrylics", weight: 0.95 },
      { phrase: "new set of nails", weight: 0.9 },
      { phrase: "nail extensions", weight: 0.9 },
      { phrase: "get acrylics", weight: 0.9 },
      { phrase: "put on nails", weight: 0.8 },
    ],
    misspellings: ["acrylics", "acrilic", "acrylix"],
  },
  {
    id: "nail-fill",
    name: "Acrylic Fill",
    category: "Manicure",
    priceLabel: "$40",
    durationMinutes: 45,
    durationLabel: "45 min",
    status: "online",
    popularRank: 4,
    keywords: [
      "fill",
      "fills",
      "infill",
      "infills",
      "refill",
      "refills",
      "fill in",
      "growing out",
      "outgrown",
    ],
    aliases: [
      { phrase: "acrylic fill", weight: 1.0 },
      { phrase: "fill in", weight: 0.9 },
      { phrase: "get a fill", weight: 0.9 },
      { phrase: "nail fill", weight: 0.9 },
      { phrase: "a fill", weight: 0.9 },
      { phrase: "need a fill", weight: 0.9 },
      { phrase: "refill my nails", weight: 0.85 },
      { phrase: "maintenance", weight: 0.7 },
    ],
    misspellings: ["fil", "refil", "infil"],
  },

  // ── Pedicure ──────────────────────────────────────────────────────────────
  {
    id: "nail-basic-pedi",
    name: "Basic Pedicure",
    category: "Pedicure",
    priceLabel: "$40",
    durationMinutes: 45,
    durationLabel: "45 min",
    status: "online",
    popularRank: 5,
    keywords: [
      "pedicure",
      "pedi",
      "feet",
      "foot",
      "toes",
      "toenails",
      "toe nails",
      "basic pedi",
    ],
    aliases: [
      { phrase: "basic pedicure", weight: 1.0 },
      { phrase: "regular pedicure", weight: 0.95 },
      { phrase: "pedicure", weight: 0.95 },
      { phrase: "get my toes done", weight: 0.85 },
      { phrase: "foot care", weight: 0.8 },
    ],
    misspellings: ["pedicur", "pedicure", "pedecure"],
  },
  {
    id: "nail-spa-pedi",
    name: "Spa Pedicure",
    category: "Pedicure",
    priceLabel: "$65",
    durationMinutes: 60,
    durationLabel: "1 hr",
    status: "online",
    popularRank: 6,
    keywords: [
      "spa pedicure",
      "deluxe pedicure",
      "luxury pedicure",
      "exfoliate",
      "foot mask",
      "foot scrub",
      "callus",
    ],
    aliases: [
      { phrase: "spa pedicure", weight: 1.0 },
      { phrase: "deluxe pedicure", weight: 0.95 },
      { phrase: "luxury pedicure", weight: 0.9 },
    ],
    misspellings: [],
  },
  {
    id: "nail-gel-pedi",
    name: "Gel Pedicure",
    category: "Pedicure",
    priceLabel: "$55",
    durationMinutes: 55,
    durationLabel: "55 min",
    status: "online",
    keywords: [
      "gel pedicure",
      "gel pedi",
      "gel toes",
      "gel toe nails",
      "long lasting pedi",
    ],
    aliases: [
      { phrase: "gel pedicure", weight: 1.0 },
      { phrase: "gel pedi", weight: 0.95 },
      { phrase: "gel on my toes", weight: 0.85 },
    ],
    misspellings: [],
  },

  // ── Add-ons / Special ─────────────────────────────────────────────────────
  {
    id: "nail-art",
    name: "Nail Art / Design",
    category: "Other",
    priceLabel: "$10+",
    durationMinutes: 20,
    durationLabel: "20+ min",
    status: "online",
    keywords: [
      "nail art",
      "design",
      "designs",
      "art",
      "pattern",
      "chrome",
      "ombre",
      "french",
      "french tip",
      "glitter",
      "decals",
      "stickers",
    ],
    aliases: [
      { phrase: "nail art", weight: 1.0 },
      { phrase: "nail design", weight: 0.95 },
      { phrase: "french tips", weight: 0.9 },
      { phrase: "chrome nails", weight: 0.9 },
      { phrase: "ombre nails", weight: 0.9 },
      { phrase: "something cute on my nails", weight: 0.75 },
    ],
    misspellings: ["nail art", "desgin"],
  },
  {
    id: "nail-removal",
    name: "Nail Removal",
    category: "Other",
    priceLabel: "$15",
    durationMinutes: 20,
    durationLabel: "20 min",
    status: "online",
    keywords: [
      "removal",
      "remove",
      "soak off",
      "take off",
      "take them off",
      "remove nails",
      "remove gel",
      "remove acrylics",
    ],
    aliases: [
      { phrase: "nail removal", weight: 1.0 },
      { phrase: "soak off", weight: 0.95 },
      { phrase: "remove my nails", weight: 0.9 },
      { phrase: "take off my nails", weight: 0.9 },
      { phrase: "remove my gel", weight: 0.85 },
      { phrase: "remove my acrylics", weight: 0.85 },
    ],
    misspellings: ["removel", "removal"],
  },
];
