import type { CatalogEntry } from "@/lib/engine/catalog";

export const MIA_CATALOG: CatalogEntry[] = [
  // ── Haircut ──────────────────────────────────────────────────────────────
  {
    id: "svc-short-cut",
    name: "Short Hair Cut / Barber Short",
    category: "Haircut",
    priceLabel: "$100",
    durationMinutes: 60,
    durationLabel: "1 hr",
    status: "online",
    popularRank: 3,
    lengthHints: ["short"],
    keywords: [
      "short",
      "barber",
      "buzz",
      "fade",
      "crop",
      "pixie",
      "men",
      "mens",
      "male",
      "guy",
      "boys",
      "close cut",
      "short cut",
      "short hair",
      "barber cut",
    ],
    aliases: [
      { phrase: "men's cut", weight: 0.95 },
      { phrase: "men's haircut", weight: 0.95 },
      { phrase: "mens haircut", weight: 0.95 },
      { phrase: "mens cut", weight: 0.95 },
      { phrase: "barber short", weight: 0.95 },
      { phrase: "short haircut", weight: 0.9 },
      { phrase: "boys haircut", weight: 0.85 },
      { phrase: "quick trim", weight: 0.7 },
    ],
    misspellings: ["haircur", "haircutt", "baber"],
  },
  {
    id: "svc-medium-long-cut",
    name: "Medium / Long Hair Cut",
    category: "Haircut",
    priceLabel: "$130",
    durationMinutes: 75,
    durationLabel: "1 hr 15 min",
    status: "online",
    popularRank: 2,
    lengthHints: ["long"],
    keywords: [
      "haircut",
      "cut",
      "trim",
      "hair cut",
      "hair trim",
      "long",
      "medium",
      "shoulder",
      "women",
      "womens",
      "female",
      "girl",
      "girls",
      "layers",
      "shaped",
      "dusting",
      "duster",
      "split ends",
    ],
    aliases: [
      { phrase: "women's cut", weight: 0.95 },
      { phrase: "women's haircut", weight: 0.95 },
      { phrase: "medium cut", weight: 0.9 },
      { phrase: "long cut", weight: 0.9 },
      { phrase: "hair trim", weight: 0.85 },
      { phrase: "trim my hair", weight: 0.85 },
      { phrase: "a trim", weight: 0.85 },
      { phrase: "get a trim", weight: 0.85 },
      { phrase: "just a trim", weight: 0.8 },
      { phrase: "a haircut", weight: 0.9 },
      { phrase: "ends trimmed", weight: 0.8 },
      { phrase: "cut my hair", weight: 0.85 },
    ],
    misspellings: ["haircutt", "haircur", "trin", "trimm"],
  },

  // ── Color ────────────────────────────────────────────────────────────────
  {
    id: "svc-root-touchup",
    name: "Root Touch-up",
    category: "Color",
    priceLabel: "$130+",
    durationMinutes: 90,
    durationLabel: "1 hr 30 min",
    status: "online",
    popularRank: 1,
    colorDirections: ["root"],
    keywords: [
      "root",
      "roots",
      "root color",
      "root colour",
      "touch up",
      "touch-up",
      "touchup",
      "regrowth",
      "outgrowth",
      "grown out",
      "grow out",
      "overgrown",
      "visible roots",
      "showing roots",
    ],
    aliases: [
      { phrase: "root touch-up", weight: 1.0 },
      { phrase: "root touchup", weight: 1.0 },
      { phrase: "touch up my roots", weight: 0.95 },
      { phrase: "roots done", weight: 0.9 },
      { phrase: "do my roots", weight: 0.9 },
      { phrase: "get my roots done", weight: 0.9 },
      { phrase: "my roots", weight: 0.85 },
      { phrase: "just roots", weight: 0.85 },
      { phrase: "just my roots", weight: 0.85 },
      { phrase: "root color", weight: 0.9 },
      { phrase: "grown-out roots", weight: 0.9 },
      { phrase: "fix my roots", weight: 0.85 },
    ],
    misspellings: ["rout touchup", "root touchup", "tuch up", "touchup"],
  },
  {
    id: "svc-full-color",
    name: "Full Color",
    category: "Color",
    priceLabel: "$300",
    durationMinutes: 120,
    durationLabel: "2 hr",
    status: "online",
    popularRank: 2,
    colorDirections: ["lighter", "darker"],
    // NOTE: "bleach", "highlights", "balayage", "platinum" etc. are NOT
    // in this list even though they're color-adjacent. The stylist
    // doesn't actually offer those techniques, and the
    // detectUnsupportedService guard (lib/unsupported-services.ts) routes
    // them to a handoff before the parser can mis-tag them as Full Color.
    keywords: [
      "color",
      "colored",
      "coloring",
      "colour",
      "coloured",
      "colouring",
      "dye",
      "dyed",
      "dyeing",
      "lighter",
      "darker",
      "blonde",
      "blonder",
      "brunette",
      "tint",
      "tinted",
      "tinting",
      "full color",
      "full colour",
      "all over",
    ],
    aliases: [
      { phrase: "full color", weight: 1.0 },
      { phrase: "full colour", weight: 1.0 },
      { phrase: "whole hair colored", weight: 0.95 },
      { phrase: "whole hair coloured", weight: 0.95 },
      { phrase: "all over color", weight: 0.95 },
      { phrase: "all-over color", weight: 0.95 },
      { phrase: "color my hair", weight: 0.9 },
      { phrase: "colour my hair", weight: 0.9 },
      { phrase: "color treatment", weight: 0.9 },
      { phrase: "colour treatment", weight: 0.9 },
      { phrase: "dye my hair", weight: 0.9 },
      { phrase: "go blonde", weight: 0.9 },
      { phrase: "go lighter", weight: 0.85 },
      { phrase: "go darker", weight: 0.85 },
      { phrase: "change my hair color", weight: 0.9 },
      { phrase: "hair color", weight: 0.85 },
      { phrase: "hair colour", weight: 0.85 },
      { phrase: "color change", weight: 0.85 },
    ],
    misspellings: ["colr", "colur", "coulor"],
  },

  // ── Treatment ────────────────────────────────────────────────────────────
  {
    id: "svc-head-spa",
    name: "Head Spa (Scalp Treatment)",
    category: "Treatment",
    priceLabel: "$150",
    durationMinutes: 60,
    durationLabel: "1 hr",
    status: "online",
    popularRank: 4,
    keywords: [
      "head spa",
      "scalp",
      "scalp treatment",
      "spa",
      "scalp massage",
      "deep clean",
      "dandruff",
      "oily scalp",
      "dry scalp",
      "head massage",
    ],
    aliases: [
      { phrase: "head spa", weight: 1.0 },
      { phrase: "scalp treatment", weight: 0.95 },
      { phrase: "scalp massage", weight: 0.9 },
      { phrase: "hair spa", weight: 0.85 },
    ],
    misspellings: ["scaltp", "scapl"],
  },
  {
    id: "svc-milbon",
    name: "Milbon Treatment",
    category: "Treatment",
    priceLabel: "$150",
    durationMinutes: 60,
    durationLabel: "1 hr",
    status: "online",
    keywords: [
      "milbon",
      "conditioning",
      "moisture",
      "repair",
      "damaged hair",
      "bond",
      "protein",
      "frizzy",
      "dry hair",
    ],
    aliases: [
      { phrase: "milbon treatment", weight: 1.0 },
      { phrase: "hair treatment", weight: 0.8 },
      { phrase: "deep conditioning", weight: 0.8 },
      { phrase: "hair repair", weight: 0.75 },
      { phrase: "bond treatment", weight: 0.75 },
    ],
    misspellings: ["milbon", "milbonn"],
  },
  {
    id: "svc-keratin",
    name: "Keratin Treatment",
    category: "Treatment",
    priceLabel: "$450",
    durationMinutes: 150,
    durationLabel: "2 hr 30 min",
    status: "online",
    keywords: [
      "keratin",
      "frizz",
      "frizzy",
      "smooth",
      "smoothing",
      "anti-frizz",
      "blowout treatment",
      "brazilian blowout",
    ],
    aliases: [
      { phrase: "keratin treatment", weight: 1.0 },
      { phrase: "keratin smoothing", weight: 0.95 },
      { phrase: "brazillian blowout", weight: 0.85 },
    ],
    misspellings: ["keretan", "keratine", "brazillian", "brazlian"],
  },

  // ── Perm ─────────────────────────────────────────────────────────────────
  {
    id: "svc-cut-down-perm",
    name: "Hair Cut + Down Perm",
    category: "Perm",
    priceLabel: "$165",
    durationMinutes: 90,
    durationLabel: "1 hr 30 min",
    status: "online",
    permStyles: ["down"],
    keywords: [
      "down perm",
      "waves",
      "wavy",
      "loose waves",
      "body wave",
      "natural wave",
    ],
    aliases: [
      { phrase: "down perm", weight: 1.0 },
      { phrase: "cut and down perm", weight: 0.95 },
      { phrase: "body wave", weight: 0.85 },
      { phrase: "loose wave perm", weight: 0.85 },
    ],
    misspellings: ["down perm"],
  },
  {
    id: "svc-mens-perm-cut",
    name: "Men's Perm + Hair Cut",
    category: "Perm",
    priceLabel: "$255",
    durationMinutes: 120,
    durationLabel: "2 hr",
    status: "online",
    permStyles: ["regular"],
    keywords: [
      "perm",
      "perms",
      "curls",
      "curly",
      "curl",
      "waves",
      "wavy",
      "men's perm",
      "male perm",
    ],
    aliases: [
      { phrase: "men's perm", weight: 1.0 },
      { phrase: "perm and cut", weight: 0.9 },
      { phrase: "curl my hair", weight: 0.8 },
    ],
    misspellings: ["perm", "purrm", "curls"],
  },
  {
    id: "svc-bang-perm",
    name: "Bang Perm",
    category: "Perm",
    priceLabel: "$100",
    durationMinutes: 60,
    durationLabel: "1 hr",
    status: "online",
    permStyles: ["regular"],
    keywords: ["bang", "bangs", "fringe", "bang perm"],
    aliases: [
      { phrase: "bang perm", weight: 1.0 },
      { phrase: "bangs perm", weight: 0.95 },
      { phrase: "fringe perm", weight: 0.9 },
    ],
    misspellings: ["bangs perm"],
  },
  {
    id: "svc-womens-regular-perm",
    name: "Women's Regular Perm",
    category: "Perm",
    priceLabel: "$280",
    durationMinutes: 180,
    durationLabel: "3 hr",
    status: "online",
    permStyles: ["regular"],
    keywords: [
      "perm",
      "perms",
      "curls",
      "curly",
      "spiral",
      "permanent waves",
      "women's perm",
      "tight curls",
      "ringlets",
    ],
    aliases: [
      { phrase: "women's perm", weight: 1.0 },
      { phrase: "regular perm", weight: 0.95 },
      { phrase: "spiral perm", weight: 0.9 },
      { phrase: "get a perm", weight: 0.85 },
      { phrase: "curly perm", weight: 0.85 },
    ],
    misspellings: ["perm", "prm"],
  },
  {
    id: "svc-womens-digital-perm",
    name: "Women's Digital Perm",
    category: "Perm",
    priceLabel: "$480",
    durationMinutes: 240,
    durationLabel: "4 hr",
    status: "consultation",
    permStyles: ["digital"],
    keywords: [
      "digital perm",
      "hot perm",
      "korean perm",
      "digital wave",
      "glamour wave",
      "s-curl",
    ],
    aliases: [
      { phrase: "digital perm", weight: 1.0 },
      { phrase: "korean perm", weight: 0.9 },
      { phrase: "hot perm", weight: 0.85 },
    ],
    misspellings: ["digital perm", "digtal perm"],
  },
  {
    id: "svc-straightening-perm",
    name: "Straightening Perm",
    category: "Perm",
    priceLabel: "$450",
    durationMinutes: 240,
    durationLabel: "4 hr",
    status: "online",
    permStyles: ["straightening"],
    keywords: [
      "straighten",
      "straightening",
      "rebond",
      "rebonding",
      "straight",
      "flat",
      "smooth",
      "japanese straightening",
      "thermal reconditioning",
    ],
    aliases: [
      { phrase: "straightening perm", weight: 1.0 },
      { phrase: "hair straightening", weight: 0.95 },
      { phrase: "rebonding", weight: 0.95 },
      { phrase: "permanent straightening", weight: 0.9 },
    ],
    misspellings: ["staightening", "streightening", "rebondig"],
  },
  // ── Other ────────────────────────────────────────────────────────────────
  {
    id: "svc-hair-wash",
    name: "Hair Wash",
    category: "Other",
    priceLabel: "$45",
    durationMinutes: 30,
    durationLabel: "30 min",
    status: "online",
    keywords: [
      "wash",
      "shampoo",
      "blow",
      "blowout",
      "blow dry",
      "rinse",
    ],
    aliases: [
      { phrase: "hair wash", weight: 1.0 },
      { phrase: "shampoo", weight: 0.9 },
      { phrase: "blowout", weight: 0.7 },
    ],
    misspellings: ["wsh"],
  },

];
